#!/usr/bin/env bun

import { access, mkdir, realpath, stat, writeFile } from "node:fs/promises";
import { dirname, isAbsolute, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

type SetupOptions = {
  root: string;
  outputDirectory?: string;
  serverName?: string;
};

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const escapeToml = (value: string) => value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
const quoteShell = (value: string) => `'${value.replace(/'/g, `'"'"'`)}'`;

export const createBridgeSetup = async ({
  root,
  outputDirectory,
  serverName = "opencut",
}: SetupOptions) => {
  if (!/^[a-zA-Z0-9_-]+$/.test(serverName)) {
    throw new Error("Server name may contain only letters, numbers, underscores, and hyphens");
  }
  const workspaceRoot = await realpath(resolve(root));
  if (!(await stat(workspaceRoot)).isDirectory()) throw new Error("OPENCUT_AGENT_ROOT must be a directory");

  const bridgeCommand = join(packageRoot, "bin", "opencut-agent");
  await access(bridgeCommand);
  const requestedOutput = outputDirectory
    ? (isAbsolute(outputDirectory) ? outputDirectory : resolve(workspaceRoot, outputDirectory))
    : join(workspaceRoot, ".opencut-agent");
  const setupDirectory = resolve(requestedOutput);
  const relativeOutput = relative(workspaceRoot, setupDirectory);
  if (relativeOutput.startsWith("..") || isAbsolute(relativeOutput)) {
    throw new Error("Setup output must remain inside OPENCUT_AGENT_ROOT");
  }
  await mkdir(setupDirectory, { recursive: true });

  const envPath = join(setupDirectory, "opencut.env");
  const mcpConfigPath = join(setupDirectory, "codex-mcp.toml");
  const manifestPath = join(setupDirectory, "setup.json");
  const envContents = `OPENCUT_AGENT_ROOT=${quoteShell(workspaceRoot)}\n`;
  const mcpContents = [
    "# Generated by OpenCut Agent Bridge. Merge this table into your Codex config when needed.",
    `[mcp_servers.${serverName}]`,
    `command = "${escapeToml(bridgeCommand)}"`,
    "startup_timeout_sec = 30",
    "tool_timeout_sec = 300",
    "",
    `[mcp_servers.${serverName}.env]`,
    `OPENCUT_AGENT_ROOT = "${escapeToml(workspaceRoot)}"`,
    "",
  ].join("\n");
  const manifest = {
    version: "1",
    serverName,
    workspaceRoot,
    bridgeCommand,
    envPath,
    mcpConfigPath,
  };

  await Promise.all([
    writeFile(envPath, envContents, { encoding: "utf8", mode: 0o600 }),
    writeFile(mcpConfigPath, mcpContents, { encoding: "utf8", mode: 0o600 }),
    writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, { encoding: "utf8", mode: 0o600 }),
  ]);
  return { ...manifest, manifestPath };
};

const parseArguments = (args: string[]) => {
  const values = new Map<string, string>();
  for (let index = 0; index < args.length; index += 1) {
    const argument = args[index]!;
    if (!argument.startsWith("--")) throw new Error(`Unknown argument: ${argument}`);
    const value = args[index + 1];
    if (!value || value.startsWith("--")) throw new Error(`${argument} requires a value`);
    values.set(argument, value);
    index += 1;
  }
  const root = values.get("--root");
  if (!root) throw new Error("Usage: opencut-setup --root <directory> [--output <directory>] [--name <server-name>]");
  return {
    root,
    outputDirectory: values.get("--output"),
    serverName: values.get("--name"),
  };
};

if (import.meta.main) {
  createBridgeSetup(parseArguments(process.argv.slice(2)))
    .then((result) => console.log(JSON.stringify(result, null, 2)))
    .catch((error: unknown) => {
      console.error(error instanceof Error ? error.message : String(error));
      process.exitCode = 1;
    });
}
